# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use Node.js LTS Alpine image
FROM node:lts-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package definitions and TypeScript config
COPY package.json package-lock.json tsconfig.json install-bridge.js ./

# Copy source code
COPY src ./src

# Install dependencies without running postinstall scripts
RUN npm install --ignore-scripts

# Compile TypeScript to JavaScript
RUN npx tsc

# Copy JSX scripts into build directory
RUN mkdir -p build/scripts && cp -r src/scripts/* build/scripts/

# Remove devDependencies to slim image
RUN npm prune --production

# Runtime image
FROM node:lts-alpine
WORKDIR /app

# Copy built app and production dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

# Default command to start MCP server
CMD ["node", "build/index.js"]
